### PR TITLE
PR #24 search - display a message when there's no results

### PR DESCRIPTION
**Pull request by MattGreyDesign**
Adds #24 enhancement

image

### CODE REVIEW

**Comment by benbrignell** [comment]
Oh man, this is perfect. Thanks.

**Comment by benbrignell** [comment]
@MattGreyDesign Hey this seems to work locally but on production search isn't working. I can't see why. Any ideas?

**Comment by benbrignell** [comment]
Ignore that @MattGreyDesign  all is good - I had a brainwave and disabled js minification and cleared server cache and it works fine. Sorry to bother you - either the old index.js was still cached or the minification was breaking something, will inspect in the morning.

**Comment by MattGreyDesign** [comment]
@benbrignell What does the minification run through? I can't seem to find anything in the pipeline, is it a post-script?

**Comment by benbrignell** [comment]
It's done by Cloudflare, I think it stripped out the frontmatter at the top

```
---

---
```

**Comment by MattGreyDesign** [comment]
So long as it minifies after Jekyll has compiled it shouldn't be too much of a problem as those are stripped from the built .js file. If that is the issue you can always hardcode the contribution url.

**Pull request merged**
