### PR TITLE
Laws of UX Design

### PR DESCRIPTION
**Pull request by arvindcheenu**
Hi **@benbrignell** !
I've added principles from a Curated List of UX Design Laws, Principles and theories proposed about human experience with the machine. Will be very useful than simply referencing standalone laws. Hope it will prove to be a good addition to the collection.

### CODE REVIEW

**Comment by benbrignell** [comment]
Hi, thanks for submitting this. I've seen this site before - it's a great site but I've been thinking about whether this should be included. It focuses on laws rather than principles and itself is a collection. It may be better to include an example for each of the groups in it's collection, for example Gestalt principles of grouping etc…

It would probably be better included as a resource rather than an example - I'm working on adding some resources soon.

**Comment by arvindcheenu** [comment]
Thanks for merging my earlier PR. This is great! Hope to contribute more to this repo.

**Comment by benbrignell** [comment]
Thanks for creating the pull request, all contributions are really appreciated. I've put it on my list for the resrouces section which I will add soon - sorry if my last message ended a bit bluntly!

**Comment by arvindcheenu** [comment]
> Thanks for creating the pull request, all contributions are really appreciated. I've put it on my list for the resrouces section which I will add soon - sorry if my last message ended a bit bluntly!

No way! What you're doing is a great service to the OSS community. I simply wish to be a part of it in any way I can.

**Pull request closed without merging**
